### ISSUE TITLE
Filter by text file

### ISSUE THREAD

**Issue by rshea0** [rshea0/tuneup-prime#64]
Allow smart playlists to be created from songs in a text file with a configurable format.

Something like this:
```yaml
rules:
  and:
    type: file
    file: playlist_1.txt
    format: [artist, title]
```

And a file as follows:
```
Artist A - Track A
Artist B - Track B
```
